### ISSUE TITLE
console.debug only exists in the browser

### ISSUE THREAD

**Issue by niieani** [aurelia/logging-console#10]
Working on server-side rendering now, and stumbled upon this when bootstrapping on NodeJS:

`console.debug` method, used [here](https://github.com/aurelia/logging-console/blob/a82125fb35a1efc6372c40b7cd5813cfbda1eb11/src/index.js#L14), does not exist in NodeJS, maybe in other contexts as well.

We should either abstract `console` in the PAL or check if `console.debug` exists and use `console.log` if it doesn't.

**Comment by niieani** [comment]
Here's a quick fix for this: https://github.com/aurelia/logging-console/pull/11

**Comment by EisenbergEffect** [comment]
I think a better fix would be to add it in the appropriate PAL implementation.

**Comment by EisenbergEffect** [comment]
We fix up console in the pal-browser already so probably need a different fixup for pal-nodejs

**Comment by niieani** [comment]
OK, fixed it in https://github.com/aurelia/pal-nodejs/commit/6eae254a9d981aa0d3a4e44979e79c314b8b7ce6.
