### ISSUE TITLE
Node doesn't have `console.debug`

### ISSUE THREAD

**Issue by aoberoi** [aurelia/logging-console#15]
**I'm submitting a feature request**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.13.3

* **Node Version:**
8.9.4

* **NPM Version:**
5.6.0

* **Language:**
all

**Current behavior:**
If I use this project on the server (node), logging to a logger with level `"debug"` does not output anything to the console. It's a noop.

**Expected/desired behavior:**
```
const logging = require('aurelia-logging');
const { ConsoleAppender } = require('aurelia-logging-console');
logging.addAppender(new ConsoleAppender());
const logger = logging.getLogger('my logger');
logger.setLevel(logging.logLevel.debug);
logger.debug('hello');
```

I expect to see the following on stdout:

```
DEBUG [my logger] hello
```

* **What is the motivation / use case for changing the behavior?**

This project states that its meant to work on the server, but not having a `debug` level on Node is less than complete support.

**Comment by aoberoi** [comment]
i just saw #10.

it's my opinion that delegating this to the `pal-nodejs` package is quite a bloated solution for what amounts to a single `|| console.log` expression.

is there any information regarding what interface the `pal*` packages are abstracting to? are there specific web standards, proposals, etc?

**Comment by Alexander-Taran** [comment]
@aoberoi what problem are you facing?
what scenario does not work for you?

**Comment by aoberoi** [comment]
@Alexander-Taran I’m not longer using this package - I don’t think my use case fits it well.

My only feedback is that I hope the maintainers consider shifting the responsibility of working around the missing `console.debug` in Node to this package, not the platform abstraction libraries. Another alternative would be to make a formal proposal for Node to gain a `console.debug` function.

**Comment by Alexander-Taran** [comment]
Thanks for your input.
Can this issue be closed then?

**Comment by aoberoi** [comment]
Yes, closing
