### ISSUE TITLE
Line numbers are not preserved.

### ISSUE THREAD

**Issue by stefek99** [aurelia/logging-console#8]
# Example:

![examples](https://cloud.githubusercontent.com/assets/249703/16453364/834538ca-3e04-11e6-8423-5cd4c76cb96f.PNG)

**Would be nice to have line numbers and being able to click form the console directly to the source.**

---

More info:
- http://stackoverflow.com/questions/13815640/a-proper-wrapper-for-console-log-with-correct-line-number
- http://stackoverflow.com/questions/11308239/console-log-wrapper-that-keeps-line-numbers-and-supports-most-methods

**Comment by EisenbergEffect** [comment]
What browser are you using?

**Comment by stefek99** [comment]
![image](https://cloud.githubusercontent.com/assets/249703/16490673/9a54ee24-3ed2-11e6-95b6-079620fb37b5.png)


*(as I visited about page it is updating now)*

**Comment by EisenbergEffect** [comment]
With errors, we have more verbose messages and stack traces that let you get what you want usually. With standard logs, I'm not sure there's a way to address this issue. It seems the only solution available works only in Chrome and is pretty hacky. Do you have a recommendation for how we can improve this in our current logger/appender architecture?

**Comment by stefek99** [comment]
No suggestions.

In fact I find it fairly inconvenient that I need to use 4 lines instead of 1:
```
import * as Logging from "aurelia-logging";
public logger: Logging.Logger;
this.logger = Logging.getLogger("stefek99");
this.logger.info("naughty Chrome, breakpoint not hit");
```

*(otherwise my build will not compile - linter functions are rather sctrict and reject ```console.log```)*

Very often I need to explicitly stick ```debugger``` because breakpoints are not hit, I think it is related how Chrome deals with ```.ts``` and ```.js```

**Comment by Alexander-Taran** [comment]
Stale since 2016
might get closed

**Comment by EisenbergEffect** [comment]
Closing this. We've made a number of improvements to the logger in debug mode to enable better stack traces. I don't know that we'll be able to do much better on the line numbers than we have today.
